Refactoring for correct using InMemory Feature
celestix/gotgproto pull request #32
Opened 2023-09-14 18:55 UTC by KoNekoD

2023-09-22 10:35 UTC, celestix requested changes

2023-09-22 17:12 UTC, KoNekoD commented on sessionMaker/sessionName.go
> +		return loadByDefault(sessionValue)
fixed 5caf1cf64640a4e7f84ee5350ce8c6a514e79236

2023-09-23 21:57 UTC, celestix approved these changes

2023-09-23 22:02 UTC, merged

2023-09-23 22:03 UTC, celestix commented
Thank you for this valuable addition to the library!