My to origin
celestix/gotgproto pull request #41
Opened 2023-12-27 22:14 UTC by KoNekoD

2023-12-29 23:07 UTC, KoNekoD commented
Okay, if you ignore me then OK.

2024-01-06 15:35 UTC, celestix requested changes

2024-01-06 15:35 UTC, celestix commented on client.go
> +	RunMiddleware func(
I can't think of any potential need of this middleware function, can you tell us what made you add this?

2024-01-06 15:35 UTC, celestix commented on client.go
> +		ctx, cancel = opts.Ctx, opts.CtxCancel
How does this external context and cancel function helps and what problem does it solve?
Also, you should consider adding the original ctx and cancel declaration of the library in an else condition as the created cancellable context would never be used in case the condition present in line 152 comes out to be true.

2024-01-06 15:35 UTC, celestix commented on client.go
>  		c.err = c.Run(c.ctx, c.initialize(&wg))
You should consider removing this because you are already calling the `c.Run` function above it. 

_Please clarify the need of RunMiddleware before proceeding to this change._

2024-01-06 23:28 UTC, KoNekoD commented on client.go
> +	RunMiddleware func(
Overlay Run function(needed for FloodWait middleware)
https://pkg.go.dev/github.com/gotd/contrib/middleware/floodwait

2024-01-06 23:32 UTC, KoNekoD commented on client.go
> +		ctx, cancel = opts.Ctx, opts.CtxCancel
According to the idea, this is needed to create a time out, before, if the account was broken, the client would wait forever, has this been fixed now? I did this to transmit a 60-second timer there. Maybe you have an idea on how to do this better? It’s just that my decision is dirty, I admit, I can’t find out the reason for the failure, and this is important! Please help with the solution, you, as a library designer, probably know whether the client will hang forever or time out, and is there such a thing at all or is there some other processing mechanism?

2024-01-06 23:34 UTC, KoNekoD commented on client.go
>  		c.err = c.Run(c.ctx, c.initialize(&wg))
fixed 6974b37fb8ad07f9a5a92c0746e5711307b5f778

2024-01-06 23:39 UTC, KoNekoD commented on client.go
>  		c.err = c.Run(c.ctx, c.initialize(&wg))
@celestix The thing is that I need access to the flood wait middleware, now I have removed it in my code, but I need to make my own handler and most likely I will still need access to this method. If you think this is freaky, then suggest how I can do this. I launch 10 clients, put them in an array, launch consumers for AMQP and put tasks there, for example, join a chat, and at the moment the task is executed, the client catches a flood wait, each client is launched according to the session that is in the Account table, I need to tag this account like floodwaited for time (and there is a time when floodwait will finish its work), so if you can offer an idea on how I can do this without wrapping RunMiddleware, then I will be glad. I myself think this is a crutch and dirty code, we both want to see this project clean) But it is closed for extension, and we need to think together how to solve this. we can discuss this in chat

2024-01-10 19:35 UTC, celestix approved these changes

2024-01-10 19:35 UTC, merged